version: "3"
services:
  backend:
    build: .
    image: backend
    environment:
      - MYSQL_ROOT_PASSWORD=Newnismo_2001
      - MYSQL_DATABASE=carsdb
      - MYSQL_USER=root
    volumes:
      - ~/backend_data:/public/product-img

networks:
  default:
    external:
      name: allnetwork
