version: "3.8"
services:
  backend:
    image: backend
    networks:
      - allnetwork
    depends_on:
      - hello_world
 
  mysqldb:
    image: mysql:8.0.23
    networks:
      - allnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=Newnismo_2001
      - MYSQL_DATABASE=carsdb
    volumes:
      - ~/backend_data:/public/product-img

networks:
  default:
    external:
      name: allnetwork