version: "3"
services:
  backend:
    container_name: backend
    build: .
    image: backend
    ports: 
      - "3000:3000"
    environment:
      - MYSQL_DATABASE=carsdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Newnismo_2001
    volumes:
      - ~/backend_data:/public/product-img

networks:
  default:
    external:
      name: allnetwork
